apiVersion: v1
kind: Service
metadata:
  labels:
    run: multi
  name: multi-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30002
  selector:
    run: multi
  type: NodePort
