apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sec-redis
  name: sec-redis
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
  containers:
  - image: redis:alpine
    name: sec-redis
